#pragma once

enum My_forward_list_errors {CANT_ALLOCATE_MEMORY, ACCESS_TO_ELEMNT_FROM_EMPTY_LIST, ITERATOR_HAVE_MOVED_OUTSIDE_LIST};

enum Shape_errors {WRONG_PARAMETERS_FOR_CIRCLE, WRONG_PARAMETERS_FOR_RECT, WRONG_PARAMETERS_FOR_SQUARE};



